version: '3.0'

services:
#  main:
#    container_name: main
#    build:
#      context: .
#    env_file:
#      - .dev.env
#    volumes:
#      - .:/app
#      - /app/node_modules
#    ports:
#      - 5000:5000
#      - 9229:9229
#    command: npm run start:dev
#    depends_on:
#      - postgres
#    restart: always
#    networks:
#      - postgres

  postgres:
    container_name: postgres
    image: postgres:14.0-alpine
    env_file:
      - .dev.env
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres

  pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4:6.12
      environment:
        PGADMIN_DEFAULT_EMAIL: "askal@ukr.net"
        PGADMIN_DEFAULT_PASSWORD: "postgre"
        PGADMIN_CONFIG_SERVER_MODE: "False"
      volumes:
        - :/var/lib/pgadmin
      ports:
        - "5050:80"
      restart: always
      networks:
        - postgres
networks:
  postgres:
    driver: bridge



