# This is a basic workflow to help you get started with Actions

name: Node.js CI
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ demo ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: install modules
        run: yarn install
      - name: build project
        run: yarn run build

